### ISSUE TITLE
Better feature check syntax

### ISSUE THREAD

**Issue by geisonbiazus** [ResultadosDigitais/feature_flagger#15]
Allow the use of sexier check sintaxes using a hash or just parameters like the following:

``` ruby
account.rollout?(email_marketing: :new_email_flow)
account.rollout?(:email_marketing, :new_email_flow)
account.rollout?(:email_marketing, :new_email_flow, :upload_image)
account.rollout?(:email_marketing: { new_email_flow: :upload_image })
```

**Comment by nandosousafr** [comment]
I think we need to let people use in order to understand if we really need to change it.

For me, we can close this for now and receive enough feedback from community/users.

what do you think @geisonbiazus ?

**Comment by geisonbiazus** [comment]
Well I am already using it and my feedback is that I realy don't like to put the `[ ]` every time I check for a rollout. If we could make it opcional would be great.

```ruby
account.rollout?(:email_marketing, :new_email_flow)
```

**Comment by nandosousafr** [comment]
Cool, I think that making `[]` optional would be great either.

**Comment by gabriel-augusto** [comment]
I agree that making the `[  ]` optional would be great! I think another good idea would be something like `account.rollout? ('some.key.here') `. It is similar to the I18n calls and in view of the Rollouts are configured in a YAML file, such a solution may be more intuitive.

**Comment by nandosousafr** [comment]
I think the current implementation is good enough after PR #16 merging.
Thanks
