### ISSUE TITLE
Uncouple gem configuration

### ISSUE THREAD

**Issue by geisonbiazus** [ResultadosDigitais/feature_flagger#2]
The gem configuration could be extracted to a separated class and then the main module could just make use of it without knowing of its internals.

**Comment by lccezinha** [comment]
@nandosousafr I would like to contrib with this change, any idea or suggestion of how to do it ?

**Comment by nandosousafr** [comment]
@lccezinha nice to hear that ;)

I think this is something very easy to do, but one thing to keep in mind is: __it must not break the current behavior__.

One suggestion is to create a `FeatureFlagger::Configuration` that holds `storage` and `yaml_file_path` attributes.

something like this:

```ruby
module FeatureFlagger
  class Configuration
    attr_accessor :storage, :yaml_file_path
    #....
  end
end
```

And replace `yield self` for  a `Configuration` instance. see:
https://github.com/ResultadosDigitais/feature_flagger/blob/master/lib/feature_flagger.rb#L13

**Comment by lccezinha** [comment]
Thanks @nandosousafr I will try it!

**Comment by geisonbiazus** [comment]
Yes @lccezinha, move it all. The main module should be as clean as possible.

**Comment by lccezinha** [comment]
Ok @geisonbiazus
