### ISSUE TITLE
Rollout Keys with numbers cause syntax error

### ISSUE THREAD

**Issue by glau** [ResultadosDigitais/feature_flagger#21]
`Account.release(:design, :2016_blue)`

Returns
`(irb):5: syntax error, unexpected tINTEGER, expecting tSTRING_CONTENT or tSTRING_DBEG or tSTRING_DVAR or tSTRING_END`

Passing the parameter as a string solves the problem
`Account.release(:design, "2016_blue")`

**Comment by nandosousafr** [comment]
@glau this happens because you can't start a symbol with numbers.

The same will happen if you try to do this on irb:

```ruby
:2015s
SyntaxError: (irb):1: syntax error, unexpected tINTEGER, expecting tSTRING_CONTENT or tSTRING_DBEG or tSTRING_DVAR or tSTRING_END
```

If you want to avoid that, don't name your keys starting with numbers.

**Comment by glau** [comment]
@nandosousafr nice to learn that, thanks for your answer! 😃 

As an enhancement suggestion:
I am a designer working in an agile organization and i was using feature_flagger to test a pull request. Since i am not a developer I could not debug that problem easily. Also the key was implemented by another developer, so I assumed everything was ok - and it wasn't.

Adding to the Usage section of the documentation the information that you shouldn't start your keys with numbers, and/or hinting the syntax for keys with numbers `:"1234_yourkey"` would increase Feature Flagger's usability by preventing implementation errors by developers and helping non-developer users (like designers and product managers) to debug the problem faster.

**Comment by nandosousafr** [comment]
@glau we're discussing this improvement at #15 :)

Thank you for the suggestion.
