### ISSUE TITLE
Release all features inside the chain

### ISSUE THREAD

**Issue by mauriciokj** [ResultadosDigitais/feature_flagger#24]
Example

``` yml
main_feature:
     feature_1:
       description: "description to first feature"
     feature_2:
       description: "second description"

     feature_3:
       description: "another description"
```

if I use `account.release (:main_feature)` it could release all internal features

**Comment by nandosousafr** [comment]
Cool @mauriciokj.

That's a great idea! if you have a suggestion how to implement that, your PR is more than welcome <3

**Comment by lccezinha** [comment]
You could read the `rollout.yml` file and find the rollout that you want, and then loop through the keys bellow the rollout hierarchique and apply the rollout for this key. What do you think ?

**Comment by nandosousafr** [comment]
@lccezinha I think it's a good start, maybe using transactions.
http://redis.io/topics/transactions

**Comment by pcasaretto** [comment]
That would probably require a more strict YML file. We currently allow an arbitrary number of nested levels.

**Comment by nandosousafr** [comment]
stale
