### ISSUE TITLE
Return all keys that model has rollout

### ISSUE THREAD

**Issue by leonardorisch** [ResultadosDigitais/feature_flagger#28]
I want to know keys under a chain that specific model has rollout

```ruby
  feature:
     sub_item1:
     sub_item2: 
     sub_item3:

  Account.released_keys(:feature)
  # [sub_item1, sub_item2]
```

**Comment by nandosousafr** [comment]
I didn't understand this. Could you elaborate with real world examples?

Thank you

**Comment by leonardorisch** [comment]
```ruby
   #rollout.yml
   customer_journey:
     notifications:
       email: 'email'
       inapp: 'inapp'
       notice: 'notice'
       


   account.release(:customer_journey, :notifications, :inapp)
   account.release(:customer_journey, :notifications, :email)
  
   account.released_keys(:customer_journey, :notifications)
   #[:inapp, :email]
```
Return only released keys for a instance of specific model

**Comment by nandosousafr** [comment]
@leonardorisch 

That's something to use only investigation purposes or would be something to be in production?

Because of performance implications, I think this has a high probability to become a headache, more than a solution.
