### ISSUE TITLE
Readme suggests to initialize feature flagger before redis

### ISSUE THREAD

**Issue by williamweckl** [ResultadosDigitais/feature_flagger#33]
If `$redis` or `Redis.current` is being set at `config/initializers/redis.rb` or any other initializer file that starts with a character after F in alphabet, Rails will load feature flagger before redis.

To workaround this, I've putted in the initializer the code below:
`require File.expand_path('../redis', __FILE__)`

Maybe we could put some warning at readme to prevent problems.

**Comment by nandosousafr** [comment]
@andrehjr suggested:

> Configure redis directly on feature_flagger initializer. Don’t reuse $redis, etc Like sidekiq does:

```
config_redis = { url: ENV["REDISTOGO_URL"],  namespace: 'mailcannon' }

Sidekiq.configure_server do |config|
  config.redis = config_redis
end
```

**Comment by nandosousafr** [comment]
Thank you for reporting this @williamweckl.

If you can, a PR will be really appreciated.

**Comment by nandosousafr** [comment]
@lekaverta let's do it together?

**Comment by lekaverta** [comment]
@nandosousafr something like that https://github.com/ResultadosDigitais/feature_flagger/pull/38?
