### ISSUE TITLE
When a key is removed of rollouts.yml, there is no clean up action

### ISSUE THREAD

**Issue by LeoSL** [ResultadosDigitais/feature_flagger#36]
When I remove a key from the `rollouts.yml` file, I'm forced to execute a `unreleased to all` command in the console to clean up the redis set.

**Comment by nandosousafr** [comment]
any idea @pcasaretto ?

**Comment by pcasaretto** [comment]
I'm afraid `unrelease_to_all` does not clean up Redis at all. It just removes one specific element from a Redis set.
https://github.com/ResultadosDigitais/feature_flagger/blob/ab88f83618c02657f51b7afa67b8c216bac031e4/lib/feature_flagger/control.rb#L34

**Comment by nandosousafr** [comment]
Ideia:

What if we provide a Rake task that traverses the rollout.yml file and clean up the removed ones from Storage.

**Comment by pcasaretto** [comment]
How does it know what has been removed?

**Comment by lekaverta** [comment]
UP cause we are removing it manually, high shit probability
Execute a rake to clean all keys which does not exist anymore looks good, @nandosousafr  :+1:. Can we implement it? Any other idea?

**Comment by nandosousafr** [comment]
@lekaverta traverse the whole tree is something really complicated. I now I think is not a good idea.

Do you have any idea?

**Comment by lekaverta** [comment]
@nandosousafr ahaha same problem from another PR

We can get all keys prefixed by resource_name, iterate in all keys returned and try to instance a Flagger, if raise an exception we know it doesn't exists and after it request a batch del in Redis.
It's just 2 requests in Redis always, the process to validate if rollout exists is as big as rollout.yml, but I don't think is a problem.
What do you think?

**Comment by nandosousafr** [comment]
What if we add a method just like this:

API
 ```ruby
Account.cleanup_keys(:email_marketing, :ab_infra)
```

redis: MULTI
```
DEL account:email_marketing:ab_infra
SREM released_features account:email_marketing:ab_infra
```

cc @lekaverta

**Comment by lekaverta** [comment]
@nandosousafr Will it used when the key exists in rollout.yml yet?

I personally prefer the rake cause we can do it scheduled and it doesn't depend from developer remember to remove one by one. Why are you against the rake?

**Comment by nandosousafr** [comment]
>  personally prefer the rake cause we can do it scheduled and it doesn't depend from developer remember to remove one by one

I agree with you @lekaverta.

How about:

1 - Get all from feature_flager using [KEY COMMAND](https://redis.io/commands/keys) using the pattern argument to get all keys stored on redis:
```
HKEYS feature_flagger
```

2 - Check if all fetched keys are present in rollout.yml;

3 - Remove keys that are present in redis but not in rollout.yml;

What do you think @lekaverta ?

**Comment by lccezinha** [comment]
I like the rake idea because it will make this process automatically for us :clap: 

@nandosousafr what is the best place to put this rake? As part of the feature_flagger gem source code, or it needs to live inside the application that uses the gem (in this case RDSM)?

**Comment by pcasaretto** [comment]
`KEYS` is a big no no for our production environment.
From the command manual page:

> Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases.

**Comment by nandosousafr** [comment]
@pcasaretto 

We should use `SCAN` then:
https://redis.io/commands/scan

from docs:
> Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using SCAN or sets.

@lccezinha FeatureFlagger should provide the rake which will be available in host applications.

**Comment by isaacsouzard** [comment]
Guys,

Taking advantage of the "Mês do Open Source da RD"
@rnnds and I are going to work on this issue.

We will discuss here the proposed solution

**Comment by felipeetchatz** [comment]
Resolved by https://github.com/ResultadosDigitais/feature_flagger/pull/51 and https://github.com/ResultadosDigitais/feature_flagger/pull/52
